### PR TITLE
Switch frame reader to gen_statem

### PR DESCRIPTION
**Pull request by AntoineGagne**
## Proposed Changes

Convert `amqp10_frame_reader` to use `gen_statem` instead of `gen_fsm` since the later is now deprecated. Issue #12 is related.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [X] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] Any dependent changes have been merged and published in related repositories

## Further Comments

Since the behaviour of the frame reader should be the same, I felt free to assume that it was already covered by the current tests.

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` for `3.8.4`, and `v3.7.x` (just in case).

**Comment by kjnilsson** [comment]
Fantastic. Thank you @AntoineGagne

**Comment by michaelklishin** [comment]
Unfortunately we have to revert this. All state machines that use `gen_fsm` need to be migrated, otherwise we keep using `gen_fsm:send_event/2` and similar functions, which means the client fails to compile from scratch (and it's a fairly weird setup anyway).

Thank you for your time, this is a good start nonetheless!

**Pull request merged**
